CREATE TABLE IF NOT EXISTS projects(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    priority integer NOT NULL,
    description text,
    deliverydate date NOT NULL
);

CREATE TABLE IF NOT EXISTS tasks(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    done BOOLEAN,
    projectId integer REFERENCES projects(id)
);

-- Insert Projects Data

INSERT INTO projects(name, priority, description, deliverydate)
    VALUES ('Make Web App', 1, 'Using Javascript', '2020-12-01');

INSERT INTO projects(name, priority, description, deliverydate)
    VALUES ('Make App', 1, 'Using Flutter', '2020-12-10');

INSERT INTO projects(name, priority, description, deliverydate)
    VALUES ('Make Desktop App', 2, 'Using C++', '2021-01-01');

-- Insert Task Data
INSERT INTO tasks(name, done, projectId)
    VALUES ('UI/UX Design', false, 1);

INSERT INTO tasks(name, done, projectId)
    VALUES ('UI/UX Design', false, 2);

INSERT INTO tasks(name, done, projectId)
    VALUES ('UI/UX Design', false, 3);

INSERT INTO tasks(name, done, projectId)
    VALUES('Team call with devs and designers', false, 1);
    
INSERT INTO tasks(name, done, projectId)
    VALUES('Team call with devs and designers', false, 2);
INSERT INTO tasks(name, done, projectId)
    VALUES('Team call with devs and designers', false, 3);
